In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_boston

**Задание 1**

In [2]:
boston = load_boston()

In [25]:
X = pd.DataFrame(boston.data, columns=boston.feature_names)
y = pd.DataFrame(boston.target, columns=['price'])

In [26]:
y.head()

price
0   24.0
1   21.6
2   34.7
3   33.4
4   36.2

In [28]:
X.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [31]:
from sklearn.linear_model import LinearRegression

In [32]:
lr = LinearRegression()

In [33]:
lr.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [34]:
y_pred = lr.predict(X_test)

In [35]:
y_pred

array([[28.64896005],
       [36.49501384],
       [15.4111932 ],
       [25.40321303],
       [18.85527988],
       [23.14668944],
       [17.3921241 ],
       [14.07859899],
       [23.03692679],
       [20.59943345],
       [24.82286159],
       [18.53057049],
       [-6.86543527],
       [21.80172334],
       [19.22571177],
       [26.19191985],
       [20.27733882],
       [ 5.61596432],
       [40.44887974],
       [17.57695918],
       [27.44319095],
       [30.1715964 ],
       [10.94055823],
       [24.02083139],
       [18.07693812],
       [15.934748  ],
       [23.12614028],
       [14.56052142],
       [22.33482544],
       [19.3257627 ],
       [22.16564973],
       [25.19476081],
       [25.31372473],
       [18.51345025],
       [16.6223286 ],
       [17.50268505],
       [30.94992991],
       [20.19201752],
       [23.90440431],
       [24.86975466],
       [13.93767876],
       [31.82504715],
       [42.56978796],
       [17.62323805],
       [27.01963242],
       [17

In [36]:
check_test = pd.DataFrame({'y_test': y_test['price'], 
                           'y_pred': y_pred.flatten()}, 
                          columns=['y_test', 'y_pred'])

In [37]:
check_test.head()

y_test     y_pred
173    23.6  28.648960
274    32.4  36.495014
491    13.6  15.411193
72     22.8  25.403213
452    16.1  18.855280

In [38]:
from sklearn.metrics import r2_score

In [56]:
r2Linear = r2_score(y_test, y_pred)
r2Linear

0.71122600574849

**Задание 2**

In [40]:
from sklearn.ensemble import RandomForestRegressor

In [41]:
regr = RandomForestRegressor(max_depth=12, random_state=42, n_estimators=1000)

In [44]:
regr.fit(X_train,  y_train.values[:, 0])


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=12,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=1000, n_jobs=None,
           oob_score=False, random_state=42, verbose=0, warm_start=False)

In [47]:
y_forest_pred = regr.predict(X_test)

In [48]:
y_forest_pred

array([22.84613791, 31.15611352, 16.29722565, 23.82103598, 17.21214765,
       21.82009184, 19.86636868, 14.75993798, 21.2352238 , 20.88310344,
       20.11747257, 19.98569932,  8.04139649, 21.47152808, 19.36056421,
       25.22123965, 18.86267442,  8.48509459, 45.8517    , 15.50158646,
       24.38461149, 23.98476408, 14.54325214, 23.5866156 , 15.02972553,
       15.26939983, 21.56389708, 13.95762333, 19.62523439, 21.0338126 ,
       19.6773222 , 23.23122956, 30.04524357, 20.12497811, 14.40836619,
       16.0512163 , 34.29058623, 19.18070898, 21.11179576, 24.23279505,
       18.63348333, 29.54059089, 45.5721    , 19.62260746, 22.57463812,
       13.9461684 , 15.72148872, 24.47776906, 19.12640766, 28.25341645,
       21.36055927, 33.88579611, 17.70003733, 26.2955691 , 45.52367393,
       21.87518392, 15.85920641, 32.42684361, 22.15625161, 20.61280516,
       25.46784804, 33.69946617, 30.09116874, 19.02315904, 27.12221893,
       16.92785667, 13.87709764, 23.11178339, 28.86580833, 15.60

In [53]:
check_test_forest = pd.DataFrame({'y_test': y_test['price'], 
                           'y_forest_pred': y_forest_pred}, 
                          columns=['y_test', 'y_forest_pred'])

In [59]:
check_test_forest.head(30)

y_test  y_forest_pred
173    23.6      22.846138
274    32.4      31.156114
491    13.6      16.297226
72     22.8      23.821036
452    16.1      17.212148
76     20.0      21.820092
316    17.8      19.866369
140    14.0      14.759938
471    19.6      21.235224
500    16.8      20.883103
218    21.5      20.117473
9      18.9      19.985699
414     7.0       8.041396
78     21.2      21.471528
323    18.5      19.360564
473    29.8      25.221240
124    18.8      18.862674
388    10.2       8.485095
195    50.0      45.851700
448    14.1      15.501586
271    25.2      24.384611
278    29.1      23.984764
30     12.7      14.543252
501    22.4      23.586616
421    14.2      15.029726
474    13.8      15.269400
79     20.3      21.563897
454    14.9      13.957623
210    21.7      19.625234
497    18.3      21.033813

In [57]:
r2RFR = r2_score(y_test, y_forest_pred)
r2RFR 

0.8749965273218174

In [58]:
if r2RFR > r2Linear:
    print('RandomForestRegressor предсказывает лучше')
else:
    print('LinearRegression предсказывает лучше')

RandomForestRegressor предсказывает лучше


**Задача 3**

In [60]:
importances = regr.feature_importances_

In [61]:
importances

array([0.03211748, 0.00154999, 0.0070941 , 0.0011488 , 0.01436832,
       0.40270459, 0.01424477, 0.06403265, 0.00496762, 0.01169177,
       0.01808961, 0.0123114 , 0.41567892])

In [62]:
np.sum(importances)

0.9999999999999994

In [67]:
importances_pd = pd.DataFrame([importances], columns=boston.feature_names)
importances_pd

CRIM       ZN     INDUS      CHAS       NOX        RM       AGE  \
0  0.032117  0.00155  0.007094  0.001149  0.014368  0.402705  0.014245   

        DIS       RAD       TAX  PTRATIO         B     LSTAT  
0  0.064033  0.004968  0.011692  0.01809  0.012311  0.415679

In [68]:
for line in boston.DESCR.split('\n'):
    print(line)

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [65]:
np.sort(importances)[::-1]

array([0.41567892, 0.40270459, 0.06403265, 0.03211748, 0.01808961,
       0.01436832, 0.01424477, 0.0123114 , 0.01169177, 0.0070941 ,
       0.00496762, 0.00154999, 0.0011488 ])

**LSTAT - 0.41567892 и RM - 0.40270459
два самых важных признака**